variables:
  DOCKER_DRIVER: overlay2

cargo:
  stage: test
  image: rust:slim
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo
  cache:
    key: .cargo
    paths:
      - .cargo
      - target
  script:
    - cargo test --all

npm:
  stage: test
  image: "registry.gitlab.com/bjrke/hidden-line/rust_wasm_npm:latest"
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo
  cache:
    key: npm
    paths:
      - hidden-line-wasm/node_modules
      - .cargo
      - target
      - hidden-line-wasm/.npm
  script:
    - cd hidden-line-wasm
    - npm i --cache .npm --prefer-offline
    - npm run test
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - hidden-line-wasm/dist

pages:
  stage: deploy
  image: alpine:latest
  script:
    - mv hidden-line-wasm/dist public
  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - main

docker_rust_wasm_npm:
  stage: .pre
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE/rust_wasm_npm" .
    - docker push "$CI_REGISTRY_IMAGE/rust_wasm_npm"
  when: manual
