test_and_build:
  stage: build
  image: "registry.gitlab.com/bjrke/hidden-line/rust_wasm_npm:latest"
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  cache:
    paths:
      - hidden-line-wasm/node_modules
      - cargo
  script:
    - rustc --version && cargo --version
    - cargo test --all
    - cd hidden-line-wasm
    - npm i
    - npm run build
    - npm run test
  artifacts:
    paths:
      - hidden-line-wasm/dist

pages:
  stage: deploy
  image: "registry.gitlab.com/bjrke/hidden-line/rust_wasm_npm:latest"
  script:
    - cp -av hidden-line-wasm/dist public
  artifacts:
    paths:
      - public
  only:
    - master

docker_rust_wasm_npm:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE/rust_wasm_npm" .
    - docker push "$CI_REGISTRY_IMAGE/rust_wasm_npm"
  when: manual
  only:
    - master
