[package]
name = "hidden-line"
description = "Hidden Line Elimination producing vectorized polygons, written in Rust, compiled to wasm, rendered as SVG"
license = "Beerware"
repository = "https://gitlab.com/bjrke/hidden-line"
version = "0.1.0"
authors = ["Jan Burkhardt <264754-bjrke@users.noreply.gitlab.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2021"
rust-version = "1.99"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.dev]
opt-level = 3
debug = 0

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = "debuginfo"
panic = "abort"

[dependencies]
wasm-bindgen = "0.2.129"
js-sys = "0.3.106"
console_error_panic_hook = "0.1.7"

[dependencies.web-sys]
version = "0.3.106"
features = [
  "AddEventListenerOptions",
  "CssStyleDeclaration",
  "Document",
  "DomRect",
  "Element",
  "Event",
  "EventTarget",
  "HtmlElement",
  "HtmlFormElement",
  "HtmlInputElement",
  "HtmlTextAreaElement",
  "KeyboardEvent",
  "Location",
  "MouseEvent",
  "Node",
  "PointerEvent",
  "SvgElement",
  "WheelEvent",
  "Window",
  "console"
]

[dev-dependencies]
wasm-bindgen-test = "0.3.79"
